apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/eduardocerqueira/linknotfound
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2023-01-13T19:57:51Z"
  generation: 4
  labels:
    app: linknotfound
    app.kubernetes.io/component: linknotfound
    app.kubernetes.io/instance: linknotfound
    app.kubernetes.io/name: linknotfound
    app.kubernetes.io/part-of: linknotfound
  name: linknotfound
  namespace: insights-qe-dev
  resourceVersion: "3835572748"
  uid: 9b6fd101-aec6-4476-890c-836a16fcbbc8
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: linknotfound:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/eduardocerqueira/linknotfound
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: linknotfound-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: linknotfound-github-webhook-secret
    type: GitHub
  - type: ConfigChange
status:
  lastVersion: 3
