kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: cron-scanner
  creationTimestamp: null
  labels:
    mode: pull
spec:
  schedule: '0 22 * * *'
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        job-name: cron-scanner
        mode: pull
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: linknotfound-scanner
              image: image-registry.openshift-image-registry.svc:5000/insights-qe-dev/linknotfound:latest
              envFrom:
                - secretRef:
                    name: linknotfound-secrets
              env:
                - name: LINKNOTFOUND_RUN
                  value: scan
                - name: CONFIG
                  value: /var/tmp/config/linknotfound.conf
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 1000m
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: "1.5Gi"
              volumeMounts:
                - name: linknotfound-conf
                  mountPath: /var/tmp/config
                  readOnly: false
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          volumes:
            - name: linknotfound-conf
              secret:
                secretName: linknotfound-conf
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
